export const data = [
  {
    "muni_id": "2",
    "muni_upper": "ACTON",
    "municipal": "Acton",
    "mapc": "1",
    "WW type": "Some sewer",
    "WW provider": "",
    "DW type": "Public Water Supply",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "10",
    "muni_upper": "ARLINGTON",
    "municipal": "Arlington",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "14",
    "muni_upper": "ASHLAND",
    "municipal": "Ashland",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "23",
    "muni_upper": "BEDFORD",
    "municipal": "Bedford",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "25",
    "muni_upper": "BELLINGHAM",
    "municipal": "Bellingham",
    "mapc": "1",
    "WW type": "Some Sewer",
    "WW provider": "Other",
    "DW type": "Public Water Supply",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "26",
    "muni_upper": "BELMONT",
    "municipal": "Belmont",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "30",
    "muni_upper": "BEVERLY",
    "municipal": "Beverly",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "?",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "0"
  },
  {
    "muni_id": "34",
    "muni_upper": "BOLTON",
    "municipal": "Bolton",
    "mapc": "1",
    "WW type": "Sewered (municipal buildings), Septic tanks (other)",
    "WW provider": "Town of Bolton",
    "DW type": "Unknown",
    "sewer_flag": "0",
    "Data_flag": "0"
  },
  {
    "muni_id": "35",
    "muni_upper": "BOSTON",
    "municipal": "Boston",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "37",
    "muni_upper": "BOXBOROUGH",
    "municipal": "Boxborough",
    "mapc": "1",
    "WW type": "Unsewered",
    "WW provider": "Septic tanks",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "40",
    "muni_upper": "BRAINTREE",
    "municipal": "Braintree",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Unknown",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "46",
    "muni_upper": "BROOKLINE",
    "municipal": "Brookline",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "48",
    "muni_upper": "BURLINGTON",
    "municipal": "Burlington",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "49",
    "muni_upper": "CAMBRIDGE",
    "municipal": "Cambridge",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "50",
    "muni_upper": "CANTON",
    "municipal": "Canton",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "51",
    "muni_upper": "CARLISLE",
    "municipal": "Carlisle",
    "mapc": "1",
    "WW type": "Septic Systems",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "57",
    "muni_upper": "CHELSEA",
    "municipal": "Chelsea",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "65",
    "muni_upper": "COHASSET",
    "municipal": "Cohasset",
    "mapc": "1",
    "WW type": "Some Sewer",
    "WW provider": "North Cohasset Sewer District, Central Cohasset Sewer District/mid/north coastal cohasset, Municipal Sewer Areas. Aquarion runs one WWTP; also a 1996 agreement that Hull will treat some of Cohasset's waste water.",
    "DW type": "Surface Water",
    "sewer_flag": "2",
    "Data_flag": "0"
  },
  {
    "muni_id": "67",
    "muni_upper": "CONCORD",
    "municipal": "Concord",
    "mapc": "1",
    "WW type": "Some Sewer (town center)",
    "WW provider": "Other",
    "DW type": "Public Water Supply",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "71",
    "muni_upper": "DANVERS",
    "municipal": "Danvers",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Danvers Sewer Division",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "0"
  },
  {
    "muni_id": "73",
    "muni_upper": "DEDHAM",
    "municipal": "Dedham",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "78",
    "muni_upper": "DOVER",
    "municipal": "Dover",
    "mapc": "1",
    "WW type": "Septic Systems",
    "WW provider": "",
    "DW type": "Some Public Water Supply",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "82",
    "muni_upper": "DUXBURY",
    "municipal": "Duxbury",
    "mapc": "1",
    "WW type": "Some sewer (250 people served by Marshfield WWTP) + Septic systems",
    "WW provider": "Marshfield WWTP?",
    "DW type": "Groundwater",
    "sewer_flag": "2",
    "Data_flag": "0"
  },
  {
    "muni_id": "92",
    "muni_upper": "ESSEX",
    "municipal": "Essex",
    "mapc": "1",
    "WW type": "Town sewer + septic tanks",
    "WW provider": "South Essex Sewer District?",
    "DW type": "Unknown",
    "sewer_flag": "2",
    "Data_flag": "0"
  },
  {
    "muni_id": "93",
    "muni_upper": "EVERETT",
    "municipal": "Everett",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "99",
    "muni_upper": "FOXBOROUGH",
    "municipal": "Foxborough",
    "mapc": "1",
    "WW type": "Some Sewer",
    "WW provider": "Other",
    "DW type": "Public Water Supply",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "100",
    "muni_upper": "FRAMINGHAM",
    "municipal": "Framingham",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "101",
    "muni_upper": "FRANKLIN",
    "municipal": "Franklin",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Local utility",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "107",
    "muni_upper": "GLOUCESTER",
    "municipal": "Gloucester",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Unknown",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "119",
    "muni_upper": "HAMILTON",
    "municipal": "Hamilton",
    "mapc": "1",
    "WW type": "Septic tanks",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": "0"
  },
  {
    "muni_id": "122",
    "muni_upper": "HANOVER",
    "municipal": "Hanover",
    "mapc": "1",
    "WW type": "Septic tanks?",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "131",
    "muni_upper": "HINGHAM",
    "municipal": "Hingham",
    "mapc": "1",
    "WW type": "Some Sewer",
    "WW provider": "Other",
    "DW type": "Unknown",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "133",
    "muni_upper": "HOLBROOK",
    "municipal": "Holbrook",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Some Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "136",
    "muni_upper": "HOLLISTON",
    "municipal": "Holliston",
    "mapc": "1",
    "WW type": "Sewer for municipal facilities; Septic for everyone else",
    "WW provider": "",
    "DW type": "Some Public Water Supply",
    "sewer_flag": "0",
    "Data_flag": "0"
  },
  {
    "muni_id": "139",
    "muni_upper": "HOPKINTON",
    "municipal": "Hopkinton",
    "mapc": "1",
    "WW type": "Sewered/Some Sewer",
    "WW provider": "Other",
    "DW type": "Public Water Supply",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "141",
    "muni_upper": "HUDSON",
    "municipal": "Hudson",
    "mapc": "1",
    "WW type": "Sewered (at least partially)",
    "WW provider": "Local system",
    "DW type": "Surface and Groundwater",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "142",
    "muni_upper": "HULL",
    "municipal": "Hull",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Local Sewer System",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "0"
  },
  {
    "muni_id": "144",
    "muni_upper": "IPSWICH",
    "municipal": "Ipswich",
    "mapc": "1",
    "WW type": "Sewered (2100 customers), potentially also some septic?",
    "WW provider": "Local wastewater department",
    "DW type": "Public Water Supply",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "155",
    "muni_upper": "LEXINGTON",
    "municipal": "Lexington",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "157",
    "muni_upper": "LINCOLN",
    "municipal": "Lincoln",
    "mapc": "1",
    "WW type": "Septic systems",
    "WW provider": "",
    "DW type": "Surface and Groundwater",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "158",
    "muni_upper": "LITTLETON",
    "municipal": "Littleton",
    "mapc": "1",
    "WW type": "Septic systems, some sewer in town center",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": "0"
  },
  {
    "muni_id": "163",
    "muni_upper": "LYNN",
    "municipal": "Lynn",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Lynn regional WWTP",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "0"
  },
  {
    "muni_id": "164",
    "muni_upper": "LYNNFIELD",
    "municipal": "Lynnfield",
    "mapc": "1",
    "WW type": "Mix of sewered and septic tanks",
    "WW provider": "Local utility",
    "DW type": "Unknown",
    "sewer_flag": "2",
    "Data_flag": "0"
  },
  {
    "muni_id": "165",
    "muni_upper": "MALDEN",
    "municipal": "Malden",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "166",
    "muni_upper": "MANCHESTER",
    "municipal": "Manchester",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Unknown",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "168",
    "muni_upper": "MARBLEHEAD",
    "municipal": "Marblehead",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "South Essex Sewer District?",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "0"
  },
  {
    "muni_id": "170",
    "muni_upper": "MARLBOROUGH",
    "municipal": "Marlborough",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "171",
    "muni_upper": "MARSHFIELD",
    "municipal": "Marshfield",
    "mapc": "1",
    "WW type": "Septic systems; some sewer systems",
    "WW provider": "Local sewer system",
    "DW type": "Unknown",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "174",
    "muni_upper": "MAYNARD",
    "municipal": "Maynard",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Some Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "175",
    "muni_upper": "MEDFIELD",
    "municipal": "Medfield",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "176",
    "muni_upper": "MEDFORD",
    "municipal": "Medford",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "177",
    "muni_upper": "MEDWAY",
    "municipal": "Medway",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Some Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "178",
    "muni_upper": "MELROSE",
    "municipal": "Melrose",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "184",
    "muni_upper": "MIDDLETON",
    "municipal": "Middleton",
    "mapc": "1",
    "WW type": "Septic systems only",
    "WW provider": "",
    "DW type": "Surface Water",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "185",
    "muni_upper": "MILFORD",
    "municipal": "Milford",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "187",
    "muni_upper": "MILLIS",
    "municipal": "Millis",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "189",
    "muni_upper": "MILTON",
    "municipal": "Milton",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "196",
    "muni_upper": "NAHANT",
    "municipal": "Nahant",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Lynn Regional WWTP",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "198",
    "muni_upper": "NATICK",
    "municipal": "Natick",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "199",
    "muni_upper": "NEEDHAM",
    "municipal": "Needham",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "207",
    "muni_upper": "NEWTON",
    "municipal": "Newton",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "208",
    "muni_upper": "NORFOLK",
    "municipal": "Norfolk",
    "mapc": "1",
    "WW type": "Sewer & small WWTP for denser sites (e.g. condos), septic systems elsewhere",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": "0"
  },
  {
    "muni_id": "213",
    "muni_upper": "NORTH READING",
    "municipal": "North Reading",
    "mapc": "1",
    "WW type": "Septic systems + a few decentralized private sewers.",
    "WW provider": "Regional utility",
    "DW type": "Surface and Groundwater",
    "sewer_flag": "0",
    "Data_flag": "0"
  },
  {
    "muni_id": "214",
    "muni_upper": "NORTHAMPTON",
    "municipal": "Northampton",
    "mapc": "0",
    "WW type": "",
    "WW provider": "",
    "DW type": "",
    "sewer_flag": "",
    "Data_flag": ""
  },
  {
    "muni_id": "219",
    "muni_upper": "NORWELL",
    "municipal": "Norwell",
    "mapc": "1",
    "WW type": "Septic systems only",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "220",
    "muni_upper": "NORWOOD",
    "municipal": "Norwood",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "229",
    "muni_upper": "PEABODY",
    "municipal": "Peabody",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "231",
    "muni_upper": "PEMBROKE",
    "municipal": "Pembroke",
    "mapc": "1",
    "WW type": "Septic/Sewered mix. Small sewers only.",
    "WW provider": "",
    "DW type": "Unknown",
    "sewer_flag": "0",
    "Data_flag": "0"
  },
  {
    "muni_id": "243",
    "muni_upper": "QUINCY",
    "municipal": "Quincy",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "244",
    "muni_upper": "RANDOLPH",
    "municipal": "Randolph",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Unknown",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "246",
    "muni_upper": "READING",
    "municipal": "Reading",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Unknown",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "248",
    "muni_upper": "REVERE",
    "municipal": "Revere",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "251",
    "muni_upper": "ROCKLAND",
    "municipal": "Rockland",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Local utility",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "0"
  },
  {
    "muni_id": "252",
    "muni_upper": "ROCKPORT",
    "municipal": "Rockport",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Local utility?",
    "DW type": "Unknown",
    "sewer_flag": "1",
    "Data_flag": "0"
  },
  {
    "muni_id": "258",
    "muni_upper": "SALEM",
    "municipal": "Salem",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Other",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "262",
    "muni_upper": "SAUGUS",
    "municipal": "Saugus",
    "mapc": "1",
    "WW type": "Sewered?",
    "WW provider": "Lynn Regional WWTP",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "0"
  },
  {
    "muni_id": "264",
    "muni_upper": "SCITUATE",
    "municipal": "Scituate",
    "mapc": "1",
    "WW type": "Some Sewer",
    "WW provider": "Other",
    "DW type": "Unknown",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "266",
    "muni_upper": "SHARON",
    "municipal": "Sharon",
    "mapc": "1",
    "WW type": "Some sewer??",
    "WW provider": "Other",
    "DW type": "Public Water Supply",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "269",
    "muni_upper": "SHERBORN",
    "municipal": "Sherborn",
    "mapc": "1",
    "WW type": "Septic Systems",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "274",
    "muni_upper": "SOMERVILLE",
    "municipal": "Somerville",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "277",
    "muni_upper": "SOUTHBOROUGH",
    "municipal": "Southborough",
    "mapc": "1",
    "WW type": "Septic Systems (even \"downtown\" has no sewer system)",
    "WW provider": "",
    "DW type": "Some Surface Water",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "284",
    "muni_upper": "STONEHAM",
    "municipal": "Stoneham",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "285",
    "muni_upper": "STOUGHTON",
    "municipal": "Stoughton",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "286",
    "muni_upper": "STOW",
    "municipal": "Stow",
    "mapc": "1",
    "WW type": "Septic systems only",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "288",
    "muni_upper": "SUDBURY",
    "municipal": "Sudbury",
    "mapc": "1",
    "WW type": "Septic systems and decentralized wastewater treatment",
    "WW provider": "Transitioned from all septic systems to ___ in 2011-2015",
    "DW type": "Public Water Supply",
    "sewer_flag": "0",
    "Data_flag": "0"
  },
  {
    "muni_id": "291",
    "muni_upper": "SWAMPSCOTT",
    "municipal": "Swampscott",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "Lynn Regional WWTP",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "298",
    "muni_upper": "TOPSFIELD",
    "municipal": "Topsfield",
    "mapc": "1",
    "WW type": "Septic Systems only",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "305",
    "muni_upper": "WAKEFIELD",
    "municipal": "Wakefield",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "307",
    "muni_upper": "WALPOLE",
    "municipal": "Walpole",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "308",
    "muni_upper": "WALTHAM",
    "municipal": "Waltham",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "314",
    "muni_upper": "WATERTOWN",
    "municipal": "Watertown",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "315",
    "muni_upper": "WAYLAND",
    "municipal": "Wayland",
    "mapc": "1",
    "WW type": "Town center is sewered, others are septic systems?",
    "WW provider": "Local utility",
    "DW type": "Public Water Supply",
    "sewer_flag": "2",
    "Data_flag": "0"
  },
  {
    "muni_id": "317",
    "muni_upper": "WELLESLEY",
    "municipal": "Wellesley",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "320",
    "muni_upper": "WENHAM",
    "municipal": "Wenham",
    "mapc": "1",
    "WW type": "Some sewer",
    "WW provider": "Other",
    "DW type": "Unknown",
    "sewer_flag": "2",
    "Data_flag": "1"
  },
  {
    "muni_id": "333",
    "muni_upper": "WESTON",
    "municipal": "Weston",
    "mapc": "1",
    "WW type": "Unsewered",
    "WW provider": "Septic tanks",
    "DW type": "Surface Water",
    "sewer_flag": "0",
    "Data_flag": ""
  },
  {
    "muni_id": "335",
    "muni_upper": "WESTWOOD",
    "municipal": "Westwood",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "336",
    "muni_upper": "WEYMOUTH",
    "municipal": "Weymouth",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Public Water Supply",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "342",
    "muni_upper": "WILMINGTON",
    "municipal": "Wilmington",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Unknown",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "344",
    "muni_upper": "WINCHESTER",
    "municipal": "Winchester",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "346",
    "muni_upper": "WINTHROP",
    "municipal": "Winthrop",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "347",
    "muni_upper": "WOBURN",
    "municipal": "Woburn",
    "mapc": "1",
    "WW type": "Sewered",
    "WW provider": "MWRA",
    "DW type": "Surface Water",
    "sewer_flag": "1",
    "Data_flag": "1"
  },
  {
    "muni_id": "350",
    "muni_upper": "WRENTHAM",
    "municipal": "Wrentham",
    "mapc": "1",
    "WW type": "Septic Systems",
    "WW provider": "",
    "DW type": "Groundwater",
    "sewer_flag": "0",
    "Data_flag": ""
  }
]